import 'package:service_reminder/core/constants/app_constants.dart';
import 'package:service_reminder/features/customers/domain/entities/customer.dart';

class CustomerDto {
  final String id;
  final String technicianId;
  final String name;
  final String? phone;
  final String? address;
  final DateTime createdAt;
  final int serviceFrequencyDays;
  final CustomerType customerType;

  const CustomerDto({
    required this.id,
    required this.technicianId,
    required this.name,
    this.phone,
    this.address,
    required this.createdAt,
    this.serviceFrequencyDays = 120,
    this.customerType = CustomerType.oneTime,
  });

  factory CustomerDto.fromJson(Map<String, dynamic> json) {
    return CustomerDto(
      id: json['id'] as String,
      technicianId: json['technician_id'] as String,
      name: json['name'] as String,
      phone: json['phone'] as String?,
      address: json['address'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      serviceFrequencyDays: (json['service_frequency_days'] as int?) ?? 120,
      customerType: _typeFromString(json['customer_type'] as String?),
    );
  }

  static CustomerType _typeFromString(String? value) =>
      value == 'amc' ? CustomerType.amc : CustomerType.oneTime;

  static String _typeToString(CustomerType type) =>
      type == CustomerType.amc ? 'amc' : 'one_time';

  /// JSON sent on insert — id and created_at are generated by Supabase.
  Map<String, dynamic> toInsertJson(String technicianId) => {
        'technician_id': technicianId,
        'name': name,
        if (phone != null) 'phone': phone,
        if (address != null) 'address': address,
        if (AppConstants.customersHasServiceFrequencyDaysColumn)
          'service_frequency_days': serviceFrequencyDays,
        if (AppConstants.customersHasCustomerTypeColumn)
          'customer_type': _typeToString(customerType),
      };

  /// PATCH payload — do not send `technician_id` or `id` here.
  Map<String, dynamic> toUpdateJson() => {
        'name': name.trim(),
        'phone': phone?.trim(),
        'address': address?.trim(),
        if (AppConstants.customersHasServiceFrequencyDaysColumn)
          'service_frequency_days': serviceFrequencyDays,
        if (AppConstants.customersHasCustomerTypeColumn)
          'customer_type': _typeToString(customerType),
      };

  Customer toDomain() => Customer(
        id: id,
        technicianId: technicianId,
        name: name,
        phone: phone,
        address: address,
        createdAt: createdAt,
        serviceFrequencyDays: serviceFrequencyDays,
        customerType: customerType,
        nextServiceAt: null,
      );
}
